"""Browser control stubs.

All functions require ``user`` and ``signature`` keyword arguments. A
``PermissionError`` is raised if the signature is invalid. Signatures should
be generated by :func:`app.utils.generate_signature` using the current user,
tool name, and sanitized arguments.
"""

from app.utils import verify_signature


def open_url(url: str, *, user: str, signature: str) -> str:
    """Pretend to open a browser window and return a message.

    Requires ``user`` and ``signature`` keyword arguments. Raises
    ``PermissionError`` if the signature is invalid. Signatures should be
    created by :func:`app.utils.generate_signature` with the current user,
    tool name, and sanitized arguments.
    """
    verify_signature(signature, user, "open_url", {"url": url})
    return f"Opened {url}"
