"""Simple web crawling and search utilities.

All functions require ``user`` and ``signature`` keyword arguments. A
``PermissionError`` is raised if the signature is invalid. Signatures should
be generated by :func:`app.utils.generate_signature` using the current user,
tool name, and sanitized arguments.
"""
from __future__ import annotations

import re
from typing import Any, Dict, List
from urllib.parse import parse_qs, unquote, urlparse

from app.utils import verify_signature
from app.utils.http_client import http_session
from bs4 import BeautifulSoup

_SEARCH_ENDPOINTS = (
    ("https://lite.duckduckgo.com/lite/", "lite"),
    ("https://duckduckgo.com/html/", "html"),
)
_JINA_PROXY_ENDPOINT = "https://r.jina.ai/http://lite.duckduckgo.com/lite/"
_USER_AGENT = "float-agent/1.0"
_JINA_LINK_RE = re.compile(r"^\s*\d+\.\[(.+?)\]\((.+?)\)\s*$")


def crawl(url: str, timeout: int = 5, *, user: str, signature: str) -> str:
    """Fetch the contents of ``url`` and return the text snippet."""
    verify_signature(
        signature, user, "crawl", {"url": url, "timeout": int(timeout or 5)}
    )
    resp = http_session.get(
        url,
        timeout=timeout,
        headers={"User-Agent": _USER_AGENT},
    )
    resp.raise_for_status()
    return resp.text[:10000]


def _clean_snippet(text: str) -> str:
    return " ".join((text or "").split())

def _decode_ddg_url(href: str | None) -> str:
    if not href:
        return ""
    if href.startswith("//"):
        href = f"https:{href}"
    parsed = urlparse(href)
    query = parse_qs(parsed.query)
    target = query.get("uddg")
    if target:
        return unquote(target[0])
    return href


def _looks_like_ddg_anomaly(text: str) -> bool:
    lowered = (text or "").lower()
    return (
        "anomaly.js" in lowered
        or "is506" in lowered
        or "captcha" in lowered
        or "verify you are a human" in lowered
    )


def _extract_lite_results(
    soup: BeautifulSoup, limit: int
) -> List[Dict[str, Any]]:
    results: List[Dict[str, Any]] = []
    links = soup.select("a.result-link")
    snippets = soup.select("td.result-snippet")
    for idx, link in enumerate(links):
        if len(results) >= limit:
            break
        title = _clean_snippet(link.get_text())
        url = _decode_ddg_url(link.get("href"))
        if not title or not url:
            continue
        snippet_text = ""
        if idx < len(snippets):
            snippet_text = _clean_snippet(snippets[idx].get_text())
        results.append(
            {"title": title, "url": url, "snippet": snippet_text}
        )
    return results


def _extract_html_results(
    soup: BeautifulSoup, limit: int
) -> List[Dict[str, Any]]:
    results: List[Dict[str, Any]] = []
    for block in soup.select(".result"):
        if len(results) >= limit:
            break
        link = block.select_one(".result__a")
        snippet = block.select_one(".result__snippet")
        if not link:
            continue
        href = link.get("href")
        title = _clean_snippet(link.get_text())
        if not href or not title:
            continue
        results.append(
            {
                "title": title,
                "url": href,
                "snippet": _clean_snippet(snippet.get_text() if snippet else ""),
            }
        )
    return results


def _extract_jina_results(text: str, limit: int) -> List[Dict[str, Any]]:
    results: List[Dict[str, Any]] = []
    lines = (text or "").splitlines()
    for idx, line in enumerate(lines):
        match = _JINA_LINK_RE.match(line.strip())
        if not match:
            continue
        title = _clean_snippet(match.group(1).replace("**", ""))
        url = _decode_ddg_url(match.group(2))
        snippet_text = ""
        for next_line in lines[idx + 1 :]:
            if not next_line.strip():
                continue
            if _JINA_LINK_RE.match(next_line.strip()):
                break
            snippet_text = _clean_snippet(next_line.replace("**", ""))
            break
        if not title or not url:
            continue
        results.append(
            {"title": title, "url": url, "snippet": snippet_text}
        )
        if len(results) >= limit:
            break
    return results


def search_web(
    query: str,
    max_results: int = 5,
    region: str = "us-en",
    *,
    user: str,
    signature: str,
    **kwargs,
) -> Dict[str, Any]:
    """Return lightweight web search results for ``query``."""
    # Backwards compatibility: some model/tool schemas use `topn`/`top_k` and
    # may include non-schema fields like `source` or `recency_days`.
    alias_max = (
        kwargs.get("topn")
        or kwargs.get("top_n")
        or kwargs.get("top_k")
        or kwargs.get("num_results")
    )
    try:
        if alias_max is not None and int(max_results or 5) == 5:
            max_results = int(alias_max)
    except Exception:
        pass
    sanitized = {
        "query": query,
        "max_results": int(max_results or 5),
        "region": region,
    }
    verify_signature(signature, user, "search_web", sanitized)
    limit = max(1, min(int(max_results or 5), 10))
    params = {"q": query, "kl": region or "us-en"}
    results: List[Dict[str, Any]] = []
    used_fallback = False
    saw_anomaly = False
    last_text = ""
    for endpoint, kind in _SEARCH_ENDPOINTS:
        request_params = dict(params)
        if kind == "html":
            request_params["ia"] = "web"
        resp = http_session.get(
            endpoint,
            params=request_params,
            timeout=10,
            headers={"User-Agent": _USER_AGENT},
        )
        resp.raise_for_status()
        last_text = resp.text or ""
        if _looks_like_ddg_anomaly(last_text):
            saw_anomaly = True
        soup = BeautifulSoup(last_text, "html.parser")
        if kind == "lite":
            results = _extract_lite_results(soup, limit)
        else:
            results = _extract_html_results(soup, limit)
        if results:
            break
    if not results:
        try:
            resp = http_session.get(
                _JINA_PROXY_ENDPOINT,
                params=params,
                timeout=10,
                headers={"User-Agent": _USER_AGENT},
            )
            resp.raise_for_status()
            last_text = resp.text or ""
            results = _extract_jina_results(last_text, limit)
            used_fallback = bool(results)
        except Exception:
            used_fallback = False
    payload: Dict[str, Any] = {
        "query": query,
        "region": region,
        "results": results,
        "count": len(results),
    }
    if used_fallback:
        if saw_anomaly:
            payload[
                "warning"
            ] = "DuckDuckGo returned a bot/anomaly page; results fetched via a proxy fallback."
        else:
            payload[
                "warning"
            ] = "Primary search returned 0 results; results fetched via a proxy fallback."
    elif not results:
        if saw_anomaly:
            payload[
                "warning"
            ] = "Search returned a bot/anomaly page; automated search may be blocked."
        else:
            payload[
                "warning"
            ] = "Search returned 0 results; the provider may be blocking automated requests."
    return payload
