"""Local file management tools.

All functions require ``user`` and ``signature`` keyword arguments. A
``PermissionError`` is raised if the signature is invalid. Signatures should
be generated by :func:`app.utils.generate_signature` using the current user,
tool name, and sanitized arguments.

Access is sandboxed:
- read_file: any path under the data directory
- list_dir: any directory under the data directory
- write_file: only paths under data/workspace
"""
from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List

from app import config as app_config
from app.utils import verify_signature


def _normalize_tool_path(path: str, *, workspace_only: bool) -> str:
    """Normalize common assistant-provided path prefixes.

    The model often emits paths like `data/workspace/foo.txt`. Our tool roots
    already point at `data/` (read) and `data/workspace/` (write), so keeping
    those prefixes duplicates segments (e.g. `data/data/workspace/...`).
    """
    raw = str(path or "").strip()
    if not raw:
        return raw
    candidate = Path(raw).expanduser()
    if candidate.is_absolute():
        return raw
    normalized = raw.replace("\\", "/")
    while normalized.startswith("./"):
        normalized = normalized[2:]
    if workspace_only:
        for prefix in ("data/workspace/", "workspace/", "data/"):
            if normalized.startswith(prefix):
                normalized = normalized[len(prefix) :]
                break
    else:
        if normalized.startswith("data/"):
            normalized = normalized[len("data/") :]
    return normalized or "."


def _resolve_rooted_path(path: str, root: Path) -> Path:
    candidate = Path(path).expanduser()
    if not candidate.is_absolute():
        candidate = root / candidate
    try:
        resolved = candidate.resolve()
    except Exception:
        resolved = candidate
    try:
        resolved.relative_to(root)
    except Exception:
        raise PermissionError(f"Path is outside allowed root: {root}")
    return resolved


def _get_data_dirs() -> tuple[Path, Path]:
    cfg = app_config.load_config()
    raw_data_dir = Path(cfg.get("data_dir") or app_config.DEFAULT_DATA_DIR)
    if not raw_data_dir.is_absolute():
        raw_data_dir = (app_config.REPO_ROOT / raw_data_dir).resolve()
    else:
        try:
            raw_data_dir = raw_data_dir.resolve()
        except Exception:
            pass
    workspace_dir = (raw_data_dir / "workspace").resolve()
    return raw_data_dir, workspace_dir


def _is_hidden_path(path: Path) -> bool:
    return any(part.startswith(".") for part in path.parts if part not in {"."})


def _relative_display_path(path: Path, root: Path) -> str:
    try:
        rel = path.relative_to(root)
    except Exception:
        return path.as_posix()
    text = rel.as_posix()
    return text or "."


def _coerce_bounded_int(
    value: Any,
    *,
    default: int,
    minimum: int,
    maximum: int,
) -> int:
    try:
        parsed = int(value)
    except Exception:
        parsed = default
    return max(minimum, min(parsed, maximum))


def list_dir(
    path: str = ".",
    workspace_only: bool = False,
    recursive: bool = False,
    include_hidden: bool = False,
    max_entries: int = 100,
    *,
    user: str,
    signature: str,
) -> Dict[str, Any]:
    """Return structured directory listings inside the managed data sandbox."""

    payload = {
        "path": path or ".",
        "workspace_only": bool(workspace_only),
        "recursive": bool(recursive),
        "include_hidden": bool(include_hidden),
        "max_entries": int(max_entries or 100),
    }
    verify_signature(signature, user, "list_dir", payload)
    data_dir, workspace_dir = _get_data_dirs()
    root = workspace_dir if workspace_only else data_dir
    limit = max(1, min(int(max_entries or 100), 200))
    normalized = _normalize_tool_path(path or ".", workspace_only=bool(workspace_only))
    resolved = _resolve_rooted_path(normalized, root)
    if not resolved.exists():
        raise FileNotFoundError(f"Directory not found: {resolved}")
    if not resolved.is_dir():
        raise NotADirectoryError(f"Not a directory: {resolved}")

    if recursive:
        candidates = sorted(
            resolved.rglob("*"),
            key=lambda entry: (
                entry.is_file(),
                _relative_display_path(entry, root).lower(),
            ),
        )
    else:
        candidates = sorted(
            resolved.iterdir(),
            key=lambda entry: (
                entry.is_file(),
                entry.name.lower(),
            ),
        )

    entries: List[Dict[str, Any]] = []
    truncated = False
    for entry in candidates:
        rel_path = _relative_display_path(entry, root)
        rel_obj = Path(rel_path)
        if not include_hidden and _is_hidden_path(rel_obj):
            continue
        item: Dict[str, Any] = {
            "name": entry.name,
            "path": rel_path,
            "type": "directory" if entry.is_dir() else "file",
        }
        try:
            stat = entry.stat()
            item["modified_at"] = float(stat.st_mtime)
            if entry.is_file():
                item["size_bytes"] = int(stat.st_size)
        except Exception:
            pass
        if len(entries) >= limit:
            truncated = True
            break
        entries.append(item)

    return {
        "path": _relative_display_path(resolved, root),
        "scope": "workspace" if workspace_only else "data",
        "root": root.as_posix(),
        "recursive": bool(recursive),
        "include_hidden": bool(include_hidden),
        "count": len(entries),
        "truncated": truncated,
        "entries": entries,
    }


def read_file(
    path: str,
    start_line: int = 1,
    line_count: int = 200,
    max_chars: int = 12000,
    *,
    user: str,
    signature: str,
) -> Dict[str, Any]:
    """Return a bounded text window from ``path``.

    Requires ``user`` and ``signature`` keyword arguments. Raises
    ``PermissionError`` if the signature is invalid. Signatures should be
    created by :func:`app.utils.generate_signature` with the current user,
    tool name, and sanitized arguments.
    """
    normalized_start_line = _coerce_bounded_int(
        start_line, default=1, minimum=1, maximum=1_000_000
    )
    normalized_line_count = _coerce_bounded_int(
        line_count, default=200, minimum=1, maximum=1000
    )
    normalized_max_chars = _coerce_bounded_int(
        max_chars, default=12000, minimum=200, maximum=20000
    )
    payload = {
        "path": path,
        "start_line": normalized_start_line,
        "line_count": normalized_line_count,
        "max_chars": normalized_max_chars,
    }
    verify_signature(signature, user, "read_file", payload)
    data_dir, _ = _get_data_dirs()
    normalized = _normalize_tool_path(path, workspace_only=False)
    resolved = _resolve_rooted_path(normalized, data_dir)
    if not resolved.exists() or not resolved.is_file():
        raise FileNotFoundError(f"File not found: {resolved}")
    raw_text = resolved.read_text(encoding="utf-8", errors="ignore")
    lines = raw_text.splitlines()
    total_lines = len(lines)
    start_index = max(0, normalized_start_line - 1)
    selected = lines[start_index : start_index + normalized_line_count]

    excerpt_lines: List[str] = []
    chars_used = 0
    truncated_by_chars = False
    for line in selected:
        separator_len = 1 if excerpt_lines else 0
        projected = chars_used + separator_len + len(line)
        if excerpt_lines and projected > normalized_max_chars:
            truncated_by_chars = True
            break
        if not excerpt_lines and len(line) > normalized_max_chars:
            excerpt_lines.append(line[:normalized_max_chars])
            chars_used = len(excerpt_lines[0])
            truncated_by_chars = True
            break
        excerpt_lines.append(line)
        chars_used = projected

    excerpt = "\n".join(excerpt_lines)
    returned_lines = len(excerpt_lines)
    end_line = (
        normalized_start_line + returned_lines - 1
        if returned_lines
        else normalized_start_line - 1
    )
    truncated_by_lines = start_index + normalized_line_count < total_lines
    has_more = False
    next_start_line = None
    if end_line < total_lines:
        has_more = True
        next_start_line = end_line + 1
    elif truncated_by_chars:
        has_more = True
        next_start_line = (
            end_line if end_line >= normalized_start_line else normalized_start_line
        )

    summary = (
        f"Read lines {normalized_start_line}-{end_line if end_line >= normalized_start_line else normalized_start_line} "
        f"of {total_lines} from {_relative_display_path(resolved, data_dir)}."
    )
    if total_lines == 0:
        summary = f"Read empty file {_relative_display_path(resolved, data_dir)}."
    elif truncated_by_chars or truncated_by_lines:
        summary += " More content is available."

    try:
        stat = resolved.stat()
        size_bytes = int(stat.st_size)
    except Exception:
        size_bytes = None

    return {
        "path": _relative_display_path(resolved, data_dir),
        "scope": "data",
        "root": data_dir.as_posix(),
        "encoding": "utf-8",
        "start_line": normalized_start_line,
        "end_line": end_line,
        "returned_line_count": returned_lines,
        "requested_line_count": normalized_line_count,
        "total_lines": total_lines,
        "max_chars": normalized_max_chars,
        "truncated": bool(truncated_by_chars or truncated_by_lines),
        "truncated_by": "chars"
        if truncated_by_chars
        else ("lines" if truncated_by_lines else None),
        "has_more": has_more,
        "next_start_line": next_start_line,
        "size_bytes": size_bytes,
        "summary": summary,
        "text": excerpt,
    }


def write_file(path: str, content: str, *, user: str, signature: str) -> str:
    """Write ``content`` to ``path`` and confirm.

    Requires ``user`` and ``signature`` keyword arguments. Raises
    ``PermissionError`` if the signature is invalid. Signatures should be
    created by :func:`app.utils.generate_signature` with the current user,
    tool name, and sanitized arguments.
    """
    verify_signature(
        signature,
        user,
        "write_file",
        {"path": path, "content": content},
    )
    _, workspace_dir = _get_data_dirs()
    normalized = _normalize_tool_path(path, workspace_only=True)
    resolved = _resolve_rooted_path(normalized, workspace_dir)
    resolved.parent.mkdir(parents=True, exist_ok=True)
    resolved.write_text(content, encoding="utf-8")
    return "written"
